"""
Version information for DG-LAB-VRCOSC
Auto-generated by scripts/generate_version.py
Do not edit this file manually!
"""

import logging
from typing import Dict

logger = logging.getLogger(__name__)

VERSION = "v0.1.1-20250829-1137-3802103"
VERSION_SHORT = "v0.1.1"

BUILD_INFO = {
    "version": "v0.1.1-20250829-1137-3802103",
    "commit_hash": "3802103dae071c5203644417765d2084c1d1ddf3",
    "commit_short": "3802103",
    "branch": "master",
    "commit_date": "2025-08-29 10:54:31 +0800",
    "build_time": "2025-08-29T11:37:35.545850",
    "python_version": "3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]",
    "platform": "win32"
}

def get_version() -> str:
    """Get the application version"""
    return VERSION

def get_version_short() -> str:
    """Get the short version (tag only)"""
    return VERSION_SHORT

def get_build_info() -> Dict[str, str]:
    """Get detailed build information"""
    return BUILD_INFO.copy()

def _format_version_lines() -> tuple[str, str, str]:
    """Format version information lines"""
    return (
        f"DG-LAB-VRCOSC Version: {VERSION}",
        f"Commit: {BUILD_INFO['commit_short']} ({BUILD_INFO['branch']})",
        f"Built: {BUILD_INFO['build_time']}"
    )

def print_version_info() -> None:
    """Print version information for debugging"""
    for line in _format_version_lines():
        print(line)

def log_version_info() -> None:
    """Log version information using logger"""
    for line in _format_version_lines():
        logger.info(line)

if __name__ == "__main__":
    # For command line usage, still use print for direct output
    print_version_info()
